# Generated by Django 4.0.4 on 2022-05-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alluser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alluser',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
    ]
