# Generated by Django 4.0.4 on 2022-05-27 07:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_alluser_is_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocart',
            name='customer',
        ),
        migrations.AddField(
            model_name='addtocart',
            name='customer',
            field=models.ManyToManyField(related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
