# Generated by Django 4.0.4 on 2022-05-27 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_remove_addtocart_customer_addtocart_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vendor',
        ),
        migrations.AddField(
            model_name='order',
            name='addtocart',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='items.addtocart'),
            preserve_default=False,
        ),
    ]
