# Generated by Django 4.0.4 on 2022-05-27 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocart',
            name='customer',
        ),
        migrations.AddField(
            model_name='addtocart',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
