# Generated by Django 4.0.4 on 2022-05-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_remove_addtocart_customer_addtocart_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
